server:
  port: 7001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: false
    register-with-eureka: false

spring:
  security:
    user:
      name: root
      password: ok